name: vumc_demo_valle
description: "A Demo Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^8.1.4
  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  sqflite: ^2.4.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

